services:
  frontend:
    container_name: frontend
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "4002:4000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - network-juzgado

  backend:
    container_name: backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - network-juzgado

  mysql:
    container_name: database
    image: mysql:9.1.0
    environment:
      MYSQL_DATABASE: "BDC_DECRETOS"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./services/database/data:/var/lib/mysql
      - ./services/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - network-juzgado
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network-juzgado:
    driver: bridge
