POST http://localhost:5002/createActa
Content-Type: application/json

{
  "id_digitador": 444555666,
  "correo_digitador": "montoyadarwin631@gmail.com",
  "datosEncabezado": {
    "juzgado": "Juzgado Sexto (6) de Pequeñas Causas Civiles y Competencia Múltiple de Bogotá D.C.",
    "juez": "MANUELA GÓMEZ ÁNGEL RANGEL",
    "ciudad": "Bogotá D.C.",
    "origen": "Juzgado Sexto (6) de Pequeñas Causas Civiles y Competencia Múltiple de Bogotá D.C.",
    "radicado": "2302-700056",
    "demandante": "OSCAR PLAZAS",
    "demandado": "ROSALBA PEÑA",
    "proceso": "EJECUTIVO DE MÍNIMA CUANTÍA",
    "provincia": "1"
  },
  "decretosAnexados": [
    {
      "id_tipo_embargo": 1,
      "tipo": "Establecimiento",
      "leyes": [
        "Por Secretaría, elabórense los oficios requeridos, y, una vez confeccionados éstos, remítanse a la Cámara de Comercio de Tunja, por la vía prevista en el art. 11 de la Ley 2213 de 2022.",
        "Parejamente, se le advierte al ejecutante que será carga y responsabilidad exclusiva suya sufragar las tasas y tarifas, y ponerse en contracto y atender las instrucciones que la autoridad registral disponga para la materialización de la medida decretada por este Juzgado.",
        "Por Secretaría, procédase de conformidad y déjense las constancias del caso."
      ],
      "descripcion": "DECRETAR EL EMBARGO Y RETENCIÓN, del establecimiento de comercio denominado “°”, identificado con Matrícula No. °, que se denuncia de propiedad del ejecutado °##. Verificada y acreditada la inscripción de dicha medida, se resolverá lo pertinente sobre su secuestro (Art. 601 CGP).",
      "dataInputs": {
        "nombreEstablecimiento": "Nombre Establecimiento",
        "direccion": "84564564 Ubicado en Tunja"
      }
    }
  ]
}