POST http://localhost:5002/createActa
Content-Type: application/json

{
  "id_digitador": 987654321,
  "correo_digitador": "jhoanestebanpv1@gmail.com",
  "datosEncabezado": {
    "juzgado": "Juzgado Ochenta y Tres (83) Civil Municipal de Bogotá D.C. Transitorio Sesenta y Cinco (65) de Pequeñas Causas Civiles y Competencia Múltiple de Bogotá D.C.",
    "juez": "MANUELA GÓMEZ ÁNGEL RANGEL",
    "ciudad": "Bogotá D.C.",
    "origen": "Juzgado Ochenta (80) Civil Municipal de Bogotá D.C.  Transitorio Sesenta y Dos (62) de Pequeñas Causas Civiles y Competencia Múltiple de Bogotá D.C.",
    "radicado": "2133-00502-06",
    "demandante": "ROSALBA MENDIETA",
    "demandado": "OSCAR PLAZAS",
    "proceso": "EJECUTIVO PARA LA EFECTIVIDAD DE LA GARANTÍA REAL",
    "provincia": "1"
  },
  "decretosAnexados": [
    {
      "id_tipo_embargo":1,
      "tipo":"Establecimiento",
      "descripcion":"DECRETAR EL EMBARGO Y RETENCIÓN, del establecimiento de comercio denominado “°”, identificado con Matrícula No. °, que se denuncia de propiedad del ejecutado °##. Verificada y acreditada la inscripción de dicha medida, se resolverá lo pertinente sobre su secuestro (Art. 601 CGP).",
      "leyes":[
          "Por Secretaría, elabórense los oficios requeridos, y, una vez confeccionados éstos, remítanse a la Cámara de Comercio de Tunja, por la vía prevista en el art. 11 de la Ley 2213 de 2022.",
          "Parejamente, se le advierte al ejecutante que será carga y responsabilidad exclusiva suya sufragar las tasas y tarifas, y ponerse en contracto y atender las instrucciones que la autoridad registral disponga para la materialización de la medida decretada por este Juzgado.",
          "Por Secretaría, procédase de conformidad y déjense las constancias del caso."
      ],
      "dataInputs":{
          "nombreEstablecimiento":"SERVIELECTRICOS SAS",
          "direccion":"52462 UBICADO EN TUNJA"
      }
    },
    {
      "id_tipo_embargo":2,
      "tipo":"Banco",
      "descripcion":"DECRETAR EL EMBARGO Y RETENCIÓN, en la cuantía y proporción permitida por la ley, de los saldos bancarios que a cualquier título existan a favor del demandado °##, y los depósitos posteriores que se produzcan, hasta completar la suma de $° de pesos.",
      "leyes":[
          "Para el cumplimiento de la orden anterior, por la vía prevista en el artículo 11 de la Ley 2213 de 2022, remítase oficio a los gerentes de las entidades financieras relacionadas en el escrito de las cautelas, para que las sumas retenidas sean puestas a disposición del juzgado, por intermedio del Banco Agrario de Colombia S.A. dentro del término de tres (3) días, so pena de responder por los perjuicios que su incumplimiento ocasione, del correspondiente pago y de incurrir en multa de dos (2) a cinco (5) salarios mínimos legales mensuales (art. 593, núms. 4 y 10 C.G.P).",
          "Adviértasele, en la respectiva comunicación a las entidades financieras, que no podrán desconocer el contenido de los oficios ni su autenticidad habida cuenta de lo dispuesto en el inciso 2 del artículo 11 de la Ley 2213 de 2022, leído en concordancia con el Concepto 2020286687 de la Superintendencia Financiera, so pena de incurrir en desacato y hacerse acreedoras de las sanciones que la ley establece.",
          "Por Secretaría, procédase de conformidad y déjense las constancias del caso."
      ],
      "dataInputs":{
          "valor":"6.500.200 millones"
      }
    },
    {
      "id_tipo_embargo":3,
      "tipo":"Salario",
      "descripcion":"DECRETAR EL EMBARGO Y RETENCIÓN, hasta del °% del salario, y prestaciones sociales del demandado °##, de conformidad con lo dispuesto por el artículo 156 y 344 del Código Sustantivo del Trabajo, y que le corresponde en calidad de empleado de °. Se limita la medida en la cantidad de $° de pesos.",
      "leyes":[
          "Para el cumplimiento de la anterior determinación se ordena OFICIAR al tesorero y/o pagador de °#°, para que del salario devengado, o de los contratos vigentes de °##, retenga la proporción del dinero antes determinada y constituya certificado de depósito a órdenes del Juzgado, previniéndole que de lo contrario responderá por dichos valores",
          "Por Secretaría, líbrense los oficios correspondientes."
      ],
      "dataInputs":{
          "porcentaje":35,
          "empresa":"UNINPAHU",
          "valor":"1.620.300 millones"
      }
    },
    {
      "id_tipo_embargo":4,
      "tipo":"Automovil",
      "descripcion":"DECRETAR EL EMBARGO Y RETENCIÓN, del vehículo automotor de placas °, de marca °, que se denuncia de propiedad del demandado °##. Verificada y acreditada la inscripción de dicha medida, se resolverá lo pertinente sobre su secuestro (Art. 601 CGP).",
      "leyes":[
          "Por Secretaría, elabórense los oficios requeridos dirigidos a la  POLICÍA NACIONAL – SIJIN para la aprehensión del vehículo y para que lo pongan a disposición de este juzgado."
      ],
      "dataInputs":{
          "placa":"TNZ06F",
          "marca":"NKD125"
      }
    },
    {
      "id_tipo_embargo":5,
      "tipo":"Fondo de Pensiones",
      "descripcion":"DECRETAR EL EMBARGO Y RETENCIÓN, hasta del 40% de la pensión del demandado °##, como pensionado del °, de conformidad con lo dispuesto por el artículo 134 de la Ley 100 de 1993, y que le corresponde en calidad pensionada. Se limita la medida en la cantidad de $° de pesos",
      "leyes":[
          "OFICIAR al tesorero y/o pagador del FOPEP, para que del salario devengado por °##, retenga la proporción del dinero antes determinada y constituya certificado de depósito a órdenes del Juzgado, previniéndole que de lo contrario responderá por dichos valores.",
          "Por Secretaría, líbrense los oficios correspondientes."
      ],
      "dataInputs":{
          "fondoPensiones":"PORVENIR",
          "valor":"25.300.000 millones"
      }
    },
    {
      "id_tipo_embargo":6,
      "tipo":"Inmueble",
      "descripcion":"DECRETAR EL EMBARGO Y RETENCIÓN, del derecho de dominio de que sea titular la demandada °##, respecto del bien distinguido con °. Verificada y acreditada la inscripción de dicha medida, se resolverá lo pertinente sobre su secuestro.",
      "leyes":[
          "Por Secretaría, elabórense los oficios requeridos, y, una vez confeccionados éstos, remítanse a la Cámara de Comercio de Tunja, por la vía prevista en el art. 11 de la Ley 2213 de 2022.",
          "Parejamente, se le advierte al ejecutante que será carga y responsabilidad exclusiva suya sufragar las tasas y tarifas, y ponerse en contracto y atender las instrucciones que la autoridad registral disponga para la materialización de la medida decretada por este Juzgado.",
          "Por Secretaría, procédase de conformidad y déjense las constancias del caso."
      ],
      "dataInputs":{
          "direccion":"FMI 123123 UBICADO EN ANTÍOQUIA"
      }
    }
  ]
}