POST http://localhost:5002/createActa
Content-Type: application/json

{
  "id_digitador": "444555666",
  "datosEncabezado": {
    "juzgado": "Juzgado Ochenta y Tres (83) Civil Municipal de Bogotá D.C. Transitorio Sesenta y Cinco (65) de Pequeñas Causas Civiles y Competencia Múltiple de Bogotá D.C.",
    "juez": "MANUELA GÓMEZ ÁNGEL RANGEL",
    "ciudad": "Bogotá D.C.",
    "origen": "Juzgado Primero Municipal de Pequeñas Causas Civiles y Competencia Múltiple de Tunja",
    "radicado": "123131321",
    "demandante": "NOMBRE DEMANDANTE",
    "demandado": "NOMBRE DEMANDADO",
    "proceso": "EJECUTIVO DE MÍNIMA CUANTÍA",
    "cod_folio": "123131"
  },
  "decretosAnexados": [
    {
      "id_tipo_embargo": 1,
      "tipo": "Establecimiento",
      "descripcion": "DECRETAR EL EMBARGO Y RETENCIÓN, del establecimiento de comercio denominado “°”, identificado con Matrícula No. °, que se denuncia de propiedad del ejecutado °##. Verificada y acreditada la inscripción de dicha medida, se resolverá lo pertinente sobre su secuestro (Art. 601 CGP).",
      "dataInputs": {
        "nombreEstablecimiento": "SERVIELECTRICOS SAS",
        "direccion": "52462 UBICADO EN TUNJA"
      }
    }
  ]
}